### ISSUE TITLE
Unable to get API KEY

### ISSUE THREAD

**Issue by mrinalraj** [EdmundsAPI/sdk-javascript#4]
http://edmunds.mashery.com/member/my-account
The page for the api key is unavailable

**Comment by abrahamcuenca** [comment]
Hi @mrinalraj  I believe mashery apis have been disabled per the announcement on the Edmunds Developer Network page (http://developer.edmunds.com/index.html) this is perhaps why the API key is unavailable. 
Sorry for the inconvenience.

**Comment by mrinalraj** [comment]
@abrahamcuenca Thanks for the information
